# Delete these routes and define your own shop routes here

acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Acme\SyliusExamplePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Acme\SyliusExamplePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~

app_shop_partial_product_index_by_on_hand:
    path: /test
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: '@SyliusShop/Product/_horizontalList.html.twig'
            repository:
                method: findAllByOnHand
                arguments: [4]
            criteria: false
        paginate: false
        limit: 100
